### ISSUE TITLE
Icons sometimes get 'stuck' on map even when changing to other maps

### ISSUE THREAD

**Issue by dethmourne** [ESOUIMods/Destinations#15]
I occasionally find that after a while I will have random icons get 'stuck' to my map, even if I change zones/maps - most commonly, I'll see a dolmen or delve that still shows up on my map when I go into town. /reloadui generally resolves the issue. Apologies for no screenshot at this time.

**Comment by dethmourne** [comment]
Screenshot at https://imgur.com/kqUjH5H.png

**Comment by Sharlikran** [comment]
Those icons do not come from this mod. I have no information on how that happens. However, what I hear from Votan is that there are mods that alter things behind the scenes. The way it was described was that mods do not allow delayed map pins or they are not aware of this delay. This is for Mini Map mods though not Destinations. It can not be resolved by this mod. Uninstalling the mod will resolve the issue and the issue does not come from Destinations.
